version: 2
jobs:
  # build:
  #   docker:
  #     - image: circleci/node:6
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-

  #     - run:
  #         name: install-dependencies
  #         command: yarn install

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  #     - run:
  #         name: lint
  #         command: npm run lint

  regression-testing:
    docker:
      - image: circleci/node:6

      - image: selenium/hub:latest
        container_name: hub
        ports:
          - 4444:4444

      - image: selenium/node-chrome-debug:latest
        depends_on:
          - hub
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444

      - image: selenium/node-firefox-debug:latest
        depends_on:
          - hub
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: test-chrome
          command: npm run ui-test

  # update-gh-pages:
  #   docker:
  #     - image: circleci/node:6
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-

  #     - run:
  #         name: install-dependencies
  #         command: yarn install

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  #     - run:
  #         name: deploy-gh-pages
  #         command: npm run gh-pages-deploy

workflows:
  version: 2
  build-all:
    jobs:
      - regression-testing:
          filters:
            branches:
              ignore:
                - gh-pages
      # - update-gh-pages:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - master
