version: 2
jobs:
  # build:
  #   docker:
  #     - image: circleci/node:6
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-

  #     - run:
  #         name: install-dependencies
  #         command: yarn install

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  #     - run:
  #         name: lint
  #         command: npm run lint

  regression-chrome:
    docker:
      - image: circleci/node:6
        environment:
          SELENIUM_BROWSER: chrome
      - image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run-selenium
          command: npm start & sh test-regression.sh localhost 3000

  regression-firefox:
    docker:
      - image: circleci/node:6
        environment:
          SELENIUM_BROWSER: firefox
      - image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run-selenium
          command: npm start & sh test-regression.sh localhost 3000

  # update-gh-pages:
  #   docker:
  #     - image: circleci/node:6
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-

  #     - run:
  #         name: install-dependencies
  #         command: yarn install

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  #     - run:
  #         name: deploy-gh-pages
  #         command: npm run gh-pages-deploy

workflows:
  version: 2
  build-all:
    jobs:
      - regression-chrome:
          filters:
            branches:
              ignore:
                - gh-pages
      - regression-firefox:
          filters:
            branches:
              ignore:
                - gh-pages
      # - update-gh-pages:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - master
