version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm start lint

  update-gh-pages:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: deploy-gh-pages
          command: ./gh-pages-update.sh

workflows:
  version: 2
  build-all:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - update-gh-pages:
          requires:
            - build
          filters:
            branches:
              only:
                - master
